---
title: "ST 558 Project 2"
author: "Kaylee Frazier and Rebecca Voelker"
date: "10/31/2021"
output: html_document
---
```{r}
#read in library
library(tidyverse)
```


```{r data, message = FALSE}

getwd()

## Read in Raw Data Using Relative Path
library(readr)
rawData <- read_csv(file = "./project2_rawdata.csv") 
rawData

## Subset Data for Entertainment Data Channel
library(dplyr)
entertainmentData <- rawData %>% filter( data_channel_is_entertainment == 1)

## Create Training and Test Data Sets
library(caret)
set.seed(500)
trainIndex <- createDataPartition(entertainmentData$shares, p = 0.7, list = FALSE)

trainData <- entertainmentData[trainIndex,]
testData <- entertainmentData[-trainIndex,]

## Printed Out Training and Test Data Sets - Can Check if you are getting matching first ~5 Observations (Using Seed = 500)
trainData
testData

```
Create new variable day_of_the_week
```{r}
#mutate new variable using weekday_is_() variables
trainDataNew <- trainData %>% mutate(day_of_the_week =   if_else(weekday_is_monday == 1, "Monday",
       if_else(weekday_is_tuesday == 1, "Tuesday",
               if_else(weekday_is_wednesday == 1, "Wednesday",
                      if_else(weekday_is_thursday == 1, "Thursday",
                              if_else(weekday_is_friday == 1, "Friday",
                                      if_else(weekday_is_saturday == 1, "Saturday", "Sunday"
                                              ))))))) 
trainDataNew
```


Numerical summary of shares by day_of_the_week
```{r}
#find mean, median, and standard deviation of shares by day_of_the_week
trainDataNew %>% group_by(day_of_the_week) %>% summarise(avg_shares = mean(shares), med_shares = median(shares), sd_shares = sd(shares))
```

